### ISSUE TITLE
Checkpoint names and retrieval

### ISSUE THREAD

**Issue by klaudworks** [2start/pyback#4]
We need to retrieve checkpoints by their metadata (e.g. some name, age, generation, tag).
If we store the metadata in the filename, we do not need to open the remote `{{CHECKPOINT_NAME}}.json` to retrieve the checkpoint. 

Questions: 
1. Which metadata should be shown to the user about his checkpoints?
2. Which metadata should identify a checkpoint and allow the user to retrieve it?
3. Should the metadata be stored inside the filename?

**Comment by klaudworks** [comment]
My suggestion:

1. Show time, user specified name, description, file-hash of the json.
2. Retrieve checkpoints by name and file-hash prefix.
3. Choose filename as: `time-name-file_hash.

**Comment by eichenroth** [comment]
Let's ignore the description feature at first.
The rest is okay with me.
